### ISSUE TITLE
About ti.pyfunc

### ISSUE THREAD

**Issue by Jack12xl** [taichi-dev/taichi_glsl#10]
#### About ti.pyfunc

So **ti.pyfunc** can be called from both Taichi and py scope. 

So is there any reason for the existence of **ti.func**(except for it takes time to refactor the previous code ?)  for now?

If **ti.func** is kind of obsolete, could you update the **ti.func** in this repo to **ti.pyfunc**? Because that make it easier to debug😂, since we do not need to explicitly call **@ti.kernel**  in our code to test.

**Comment by archibate** [comment]
`ti.pyfunc` will **not be accelerated by Taichi** when called from Python-scope.

**Comment by Jack12xl** [comment]
###### `ti.pyfunc` will **not be accelerated by Taichi** when called from Python-scope.

Ok I see. I didn't notice that. So `ti.pyfunc` could be treated as a normal Python function if called from Python-scope right ?


But `ti.pyfunc` can be called in Python-scope while `ti.func`  can't. As a result, `ti.pyfun` still has advantage than `ti.func`. 

So compared to `ti.pyfunc`,  is `ti.func`  rather served as a **warning** when users wanna make their program paralleled with `ti.func`in Python-scope ?

**Comment by archibate** [comment]
Exactly, we want to confirm people **know what they're doing** by using pyfunc.

> As a result, ti.pyfun still has advantage than ti.func.

In fact, pyfunc is not a public API at all, it was only mean to **make funcs like `ti.Vector.dot` work in Python-scope too**. End-users should use it on their own risk.

**Comment by Jack12xl** [comment]
I see. Thanks for the reply!  I am closing it now.
