### ISSUE TITLE
Error occurred when running example sdf_rt1.py

### ISSUE THREAD

**Issue by limberc** [taichi-dev/taichi_glsl#5]
[E 08/18/20 00:35:32.302] [codegen_llvm.cpp:visit@301] Assertion failure: from != to

                            * Taichi Core - Stack Traceback *                             
==========================================================================================
|                       Module |  Offset | Function                                      |
|----------------------------------------------------------------------------------------|
*               taichi_core.so |     110 | taichi::Logger::error(std::__1::basic_string< |
                                         | char, std::__1::char_traits<char>, std::__1:: |
                                         | allocator<char> > const&, bool)               |
*               taichi_core.so |    3378 | taichi::lang::CodeGenLLVM::visit(taichi::lang |
                                         | ::UnaryOpStmt*)                               |
*               taichi_core.so |      43 | taichi::lang::CodeGenLLVM::visit(taichi::lang |
                                         | ::Block*)                                     |
*               taichi_core.so |     786 | taichi::lang::CodeGenLLVMCPU::create_offload_ |
                                         | range_for(taichi::lang::OffloadedStmt*)       |
*               taichi_core.so |    1159 | taichi::lang::CodeGenLLVMCPU::visit(taichi::l |
                                         | ang::OffloadedStmt*)                          |
*               taichi_core.so |      43 | taichi::lang::CodeGenLLVM::visit(taichi::lang |
                                         | ::Block*)                                     |
*               taichi_core.so |     103 | taichi::lang::CodeGenLLVM::emit_to_module()   |
*               taichi_core.so |      25 | taichi::lang::CodeGenLLVM::gen()              |
*               taichi_core.so |     123 | taichi::lang::CodeGenCPU::codegen()           |
*               taichi_core.so |      97 | taichi::lang::KernelCodeGen::compile()        |
*               taichi_core.so |     251 | taichi::lang::Program::compile(taichi::lang:: |
                                         | Kernel&)                                      |
*               taichi_core.so |      62 | taichi::lang::Kernel::compile()               |
*               taichi_core.so |     136 | taichi::lang::Kernel::operator()()            |
*               taichi_core.so |     103 | void pybind11::cpp_function::initialize<taich |
                                         | i::export_lang(pybind11::module&)::$_9, void, |
                                         |  taichi::lang::Kernel*, pybind11::name, pybin |
                                         | d11::is_method, pybind11::sibling>(taichi::ex |
                                         | port_lang(pybind11::module&)::$_9&&, void (*) |
                                         | (taichi::lang::Kernel*), pybind11::name const |
                                         | &, pybind11::is_method const&, pybind11::sibl |
                                         | ing const&)::'lambda'(pybind11::detail::funct |
                                         | ion_call&)::__invoke(pybind11::detail::functi |
                                         | on_call&)                                     |
*               taichi_core.so |    4075 | pybind11::cpp_function::dispatcher(_object*,  |
                                         | _object*, _object*)                           |
*                       python |     483 | (null)                                        |
*                       python |     111 | (null)                                        |
*                       python |     130 | (null)                                        |
*                       python |     130 | (null)                                        |
*                       python |     370 | (null)                                        |
*                       python |     179 | (null)                                        |
*                       python |     453 | (null)                                        |
*                       python |   46111 | (null)                                        |
*                       python |     414 | (null)                                        |
*                       python |     231 | (null)                                        |
*                       python |   46668 | (null)                                        |
*                       python |     414 | (null)                                        |
*                       python |     231 | (null)                                        |
*                       python |     189 | (null)                                        |
*                       python |     130 | (null)                                        |
*                       python |   46668 | (null)                                        |
*                       python |     414 | (null)                                        |
*                       python |     195 | (null)                                        |
*                       python |     183 | (null)                                        |
*                       python |   46111 | (null)                                        |
*                       python |     414 | (null)                                        |
*                       python |     256 | (null)                                        |
*                       python |     391 | (null)                                        |
*                       python |    9635 | (null)                                        |
*                       python |     125 | (null)                                        |
*                libdyld.dylib |       1 | (null)                                        |
*                          ??? |       2 | (null)                                        |
==========================================================================================

Internal Error occurred, check this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
Traceback (most recent call last):
  File "/Users/limber/Documents/code/taichi_glsl/examples/sdf_rt1.py", line 85, in <module>
    render()
  File "/Users/limber/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 578, in wrapped
    return primal(*args, **kwargs)
  File "/Users/limber/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 506, in __call__
    return self.compiled_functions[key](*args)
  File "/Users/limber/anaconda3/lib/python3.7/site-packages/taichi/lang/kernel.py", line 466, in func__
    t_kernel()
RuntimeError: [codegen_llvm.cpp:visit@301] Assertion failure: from != to

Process finished with exit code 1

**Comment by limberc** [comment]
Same error when running `sdf_rt2.py`.

**Comment by archibate** [comment]
Seems removing `ti.core.toggle_advanced_optimization` fixes the issue.
